export const notAnsweredQuizzes = [
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d196',
    title: 'UI',
    search: 'ui',
    shortDescription: 'Um quiz sobre UI que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 3,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 1,
  },
  {
    id: '95b93857-476d-450d-b9a7-0ef0bd6c2cc5',
    title: 'Conceitos básicos de HTML',
    search: 'html',
    shortDescription: 'Um quiz sobre HTML que vai mudar sua vida!',
    imgSrc:
      'https://www.hostinger.com.br/tutoriais/wp-content/uploads/sites/12/2018/07/Como-inserir-imagem-ou-logo-usando-HTML-no-seu-site-1.png',
    numOfQuestions: 4,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
  {
    id: 'e3a8c1c8-cdc8-4939-b2ac-ad682707937d',
    title: 'HTML avançado',
    search: 'html',
    shortDescription: 'Conceitos avançados de HTML',
    imgSrc:
      'https://marquesfernandes.com/wp-content/uploads/2020/04/florian-olivo-4hbJ-eymZ1o-unsplash.jpg',
    numOfQuestions: 4,
    difficulty: 'hard',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1961',
    title: 'UI',
    search: 'ui',
    shortDescription: 'Um quiz sobre UI que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 3,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 1,
  },
  {
    id: '95b93857-476d-450d-b9a7-0ef0bd6c2cc51',
    title: 'Conceitos básicos de HTML',
    search: 'html',
    shortDescription: 'Um quiz sobre HTML que vai mudar sua vida!',
    imgSrc:
      'https://www.hostinger.com.br/tutoriais/wp-content/uploads/sites/12/2018/07/Como-inserir-imagem-ou-logo-usando-HTML-no-seu-site-1.png',
    numOfQuestions: 4,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
  {
    id: 'e3a8c1c8-cdc8-4939-b2ac-ad682707937d1',
    title: 'HTML avançado',
    search: 'html',
    shortDescription: 'Conceitos avançados de HTML',
    imgSrc:
      'https://marquesfernandes.com/wp-content/uploads/2020/04/florian-olivo-4hbJ-eymZ1o-unsplash.jpg',
    numOfQuestions: 4,
    difficulty: 'hard',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1962',
    title: 'UI',
    search: 'ui',
    shortDescription: 'Um quiz sobre UI que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 3,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 1,
  },
  {
    id: '95b93857-476d-450d-b9a7-0ef0bd6c2cc52',
    title: 'Conceitos básicos de HTML',
    search: 'html',
    shortDescription: 'Um quiz sobre HTML que vai mudar sua vida!',
    imgSrc:
      'https://www.hostinger.com.br/tutoriais/wp-content/uploads/sites/12/2018/07/Como-inserir-imagem-ou-logo-usando-HTML-no-seu-site-1.png',
    numOfQuestions: 4,
    difficulty: 'easy',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
  {
    id: 'e3a8c1c8-cdc8-4939-b2ac-ad682707937d2',
    title: 'HTML avançado',
    search: 'html',
    shortDescription: 'Conceitos avançados de HTML',
    imgSrc:
      'https://marquesfernandes.com/wp-content/uploads/2020/04/florian-olivo-4hbJ-eymZ1o-unsplash.jpg',
    numOfQuestions: 4,
    difficulty: 'hard',
    isAnswered: false,
    answeredDate: null,
    numOfCorrectAnswers: null,
  },
];

export const answeredQuizzes = [
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d196',
    title: 'UI',
    search: 'ui',
    shortDescription: 'Um quiz sobre UI que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 3,
    difficulty: 'easy',
    isAnswered: true,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 1,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1961',
    title: 'CSS',
    search: 'ui',
    shortDescription: 'Um quiz sobre CSS que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 10,
    difficulty: 'easy',
    isAnswered: true,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 8,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1962',
    title: 'React.js',
    search: 'ui',
    shortDescription: 'Um quiz sobre React.js que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 8,
    difficulty: 'hard',
    isAnswered: true,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 3,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1963',
    title: 'Vue.js',
    search: 'ui',
    shortDescription: 'Um quiz sobre Vue.js que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 12,
    difficulty: 'hard',
    isAnswered: true,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 6,
  },
  {
    id: '224a68d0-d49a-4992-8b00-e93c0960d1946',
    title: 'Python',
    search: 'ui',
    shortDescription: 'Um quiz sobre Python que vai mudar sua vida!',
    imgSrc:
      'https://sujeitoprogramador.com/wp-content/uploads/2020/12/uiDesign-1.png',
    numOfQuestions: 3,
    difficulty: 'easy',
    isAnswered: true,
    answeredDate: '2022-06-21 22:32',
    numOfCorrectAnswers: 3,
  },
];
