export const ACTIVATE_QUIZ = 'ACTIVATE_QUIZ';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const SET_NUM_OF_QUESTIONS = 'SET_NUM_OF_QUESTIONS';
export const INCREMENT_CORRECT_ANSWERS = 'INCREMENT_CORRECT_ANSWERS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION';
export const LOADING_QUESTIONS = 'LOADING_QUESTIONS';
export const RESTART_QUIZ = 'RESTART_QUIZ';
